-- LIS Login schema (Oracle)
-- Map from frontend types:
-- FacilityOption, LabAreaOption, LoginRequestDraft, SessionBootstrapState, LoginAttemptLog

-- ==========================================================
-- 1) Master: Facilities (Co so)
-- ==========================================================
CREATE TABLE LIS_FACILITY (
  ID            VARCHAR2(36) DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
  CODE          VARCHAR2(30) NOT NULL,
  NAME          VARCHAR2(200) NOT NULL,
  IS_ACTIVE     CHAR(1) DEFAULT 'Y' NOT NULL,
  CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_LIS_FACILITY PRIMARY KEY (ID),
  CONSTRAINT UQ_LIS_FACILITY_CODE UNIQUE (CODE),
  CONSTRAINT CK_LIS_FACILITY_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

-- ==========================================================
-- 2) Master: Lab Areas (Khu XN)
-- ==========================================================
CREATE TABLE LIS_LAB_AREA (
  ID            VARCHAR2(36) DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
  FACILITY_ID   VARCHAR2(36) NOT NULL,
  CODE          VARCHAR2(30) NOT NULL,
  NAME          VARCHAR2(200) NOT NULL,
  IS_ACTIVE     CHAR(1) DEFAULT 'Y' NOT NULL,
  CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_LIS_LAB_AREA PRIMARY KEY (ID),
  CONSTRAINT FK_LIS_LAB_AREA_FACILITY FOREIGN KEY (FACILITY_ID)
    REFERENCES LIS_FACILITY (ID),
  CONSTRAINT UQ_LIS_LAB_AREA_CODE_FAC UNIQUE (FACILITY_ID, CODE),
  CONSTRAINT CK_LIS_LAB_AREA_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

-- ==========================================================
-- 3) Users (username/password)
-- NOTE: Store PASSWORD_HASH only, never plain password
-- ==========================================================
CREATE TABLE LIS_USER_ACCOUNT (
  ID                VARCHAR2(36) DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
  USERNAME          VARCHAR2(100) NOT NULL,
  DISPLAY_NAME      VARCHAR2(200),
  PASSWORD_HASH     VARCHAR2(255) NOT NULL,
  IS_ACTIVE         CHAR(1) DEFAULT 'Y' NOT NULL,
  FAILED_ATTEMPTS   NUMBER(5) DEFAULT 0 NOT NULL,
  LAST_LOGIN_AT     TIMESTAMP(6),
  CREATED_AT        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_LIS_USER_ACCOUNT PRIMARY KEY (ID),
  CONSTRAINT UQ_LIS_USER_ACCOUNT_USERNAME UNIQUE (USERNAME),
  CONSTRAINT CK_LIS_USER_ACCOUNT_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
  CONSTRAINT CK_LIS_USER_ACCOUNT_FAILED CHECK (FAILED_ATTEMPTS >= 0)
);

-- ==========================================================
-- 4) RBAC master roles
-- ==========================================================
CREATE TABLE LIS_ROLE (
  ID            VARCHAR2(36) DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
  CODE          VARCHAR2(50) NOT NULL,
  NAME          VARCHAR2(100) NOT NULL,
  IS_ACTIVE     CHAR(1) DEFAULT 'Y' NOT NULL,
  CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_LIS_ROLE PRIMARY KEY (ID),
  CONSTRAINT UQ_LIS_ROLE_CODE UNIQUE (CODE),
  CONSTRAINT CK_LIS_ROLE_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

-- ==========================================================
-- 5) RBAC user-role assignment
-- ==========================================================
CREATE TABLE LIS_USER_ROLE (
  ID            VARCHAR2(36) DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
  USER_ID       VARCHAR2(36) NOT NULL,
  ROLE_ID       VARCHAR2(36) NOT NULL,
  ASSIGNED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_LIS_USER_ROLE PRIMARY KEY (ID),
  CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID)
    REFERENCES LIS_USER_ACCOUNT (ID),
  CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID)
    REFERENCES LIS_ROLE (ID),
  CONSTRAINT UQ_USER_ROLE UNIQUE (USER_ID, ROLE_ID)
);

-- ==========================================================
-- 6) Authorization scope: which user can use which facility/lab area
-- ==========================================================
CREATE TABLE LIS_USER_SCOPE (
  ID            VARCHAR2(36) DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
  USER_ID       VARCHAR2(36) NOT NULL,
  FACILITY_ID   VARCHAR2(36) NOT NULL,
  LAB_AREA_ID   VARCHAR2(36) NOT NULL,
  IS_ACTIVE     CHAR(1) DEFAULT 'Y' NOT NULL,
  CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_LIS_USER_SCOPE PRIMARY KEY (ID),
  CONSTRAINT FK_LIS_USER_SCOPE_USER FOREIGN KEY (USER_ID)
    REFERENCES LIS_USER_ACCOUNT (ID),
  CONSTRAINT FK_LIS_USER_SCOPE_FACILITY FOREIGN KEY (FACILITY_ID)
    REFERENCES LIS_FACILITY (ID),
  CONSTRAINT FK_LIS_USER_SCOPE_LAB_AREA FOREIGN KEY (LAB_AREA_ID)
    REFERENCES LIS_LAB_AREA (ID),
  CONSTRAINT UQ_LIS_USER_SCOPE UNIQUE (USER_ID, FACILITY_ID, LAB_AREA_ID),
  CONSTRAINT CK_LIS_USER_SCOPE_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

-- ==========================================================
-- 7) Session bootstrap state persistence
-- Maps to: SessionBootstrapState + LoginRequestDraft.workDate
-- ==========================================================
CREATE TABLE LIS_SESSION (
  ID                VARCHAR2(36) DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
  SESSION_TOKEN     VARCHAR2(255) NOT NULL,
  USER_ID           VARCHAR2(36) NOT NULL,
  FACILITY_ID       VARCHAR2(36) NOT NULL,
  LAB_AREA_ID       VARCHAR2(36) NOT NULL,
  WORK_DATE         DATE NOT NULL,
  STATUS            VARCHAR2(20) DEFAULT 'success' NOT NULL,
  MESSAGE           VARCHAR2(500),
  REAUTH_REQUIRED   CHAR(1) DEFAULT 'N' NOT NULL,
  ISSUED_AT         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  EXPIRES_AT        TIMESTAMP(6),
  LAST_ATTEMPT_AT   TIMESTAMP(6),
  CREATED_AT        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_LIS_SESSION PRIMARY KEY (ID),
  CONSTRAINT UQ_LIS_SESSION_TOKEN UNIQUE (SESSION_TOKEN),
  CONSTRAINT FK_LIS_SESSION_USER FOREIGN KEY (USER_ID)
    REFERENCES LIS_USER_ACCOUNT (ID),
  CONSTRAINT FK_LIS_SESSION_FACILITY FOREIGN KEY (FACILITY_ID)
    REFERENCES LIS_FACILITY (ID),
  CONSTRAINT FK_LIS_SESSION_LAB_AREA FOREIGN KEY (LAB_AREA_ID)
    REFERENCES LIS_LAB_AREA (ID),
  CONSTRAINT CK_LIS_SESSION_STATUS CHECK (STATUS IN ('idle', 'loading', 'success', 'error')),
  CONSTRAINT CK_LIS_SESSION_REAUTH CHECK (REAUTH_REQUIRED IN ('Y', 'N'))
);

-- ==========================================================
-- 8) Non-sensitive login attempt logs
-- Maps to: LoginAttemptLog
-- ==========================================================
CREATE TABLE LIS_LOGIN_ATTEMPT_LOG (
  ID            VARCHAR2(36) DEFAULT RAWTOHEX(SYS_GUID()) NOT NULL,
  OCCURRED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  EVENT_TYPE    VARCHAR2(30) NOT NULL,
  USERNAME      VARCHAR2(100),
  FACILITY_ID   VARCHAR2(36),
  LAB_AREA_ID   VARCHAR2(36),
  ERROR_CODE    VARCHAR2(100),
  SESSION_ID    VARCHAR2(36),
  CONSTRAINT PK_LIS_LOGIN_ATTEMPT_LOG PRIMARY KEY (ID),
  CONSTRAINT FK_LIS_LOG_FACILITY FOREIGN KEY (FACILITY_ID)
    REFERENCES LIS_FACILITY (ID),
  CONSTRAINT FK_LIS_LOG_LAB_AREA FOREIGN KEY (LAB_AREA_ID)
    REFERENCES LIS_LAB_AREA (ID),
  CONSTRAINT FK_LIS_LOG_SESSION FOREIGN KEY (SESSION_ID)
    REFERENCES LIS_SESSION (ID),
  CONSTRAINT CK_LIS_LOG_EVENT_TYPE CHECK (EVENT_TYPE IN ('lookup_load', 'submit', 'submit_success', 'submit_error'))
);

-- ==========================================================
-- 9) Performance indexes
-- ==========================================================
CREATE INDEX IX_LIS_LAB_AREA_FACILITY ON LIS_LAB_AREA (FACILITY_ID, IS_ACTIVE);
CREATE INDEX IX_LIS_USER_ROLE_USER ON LIS_USER_ROLE (USER_ID);
CREATE INDEX IX_LIS_USER_ROLE_ROLE ON LIS_USER_ROLE (ROLE_ID);
CREATE INDEX IX_LIS_USER_SCOPE_USER ON LIS_USER_SCOPE (USER_ID, IS_ACTIVE);
CREATE INDEX IX_LIS_USER_SCOPE_FAC_AREA ON LIS_USER_SCOPE (FACILITY_ID, LAB_AREA_ID, IS_ACTIVE);
CREATE INDEX IX_LIS_SESSION_USER ON LIS_SESSION (USER_ID, ISSUED_AT DESC);
CREATE INDEX IX_LIS_LOG_OCCURRED_AT ON LIS_LOGIN_ATTEMPT_LOG (OCCURRED_AT DESC);
CREATE INDEX IX_LIS_LOG_EVENT ON LIS_LOGIN_ATTEMPT_LOG (EVENT_TYPE, OCCURRED_AT DESC);

-- ==========================================================
-- 10) Seed data for current frontend mock options
-- ==========================================================
INSERT INTO LIS_FACILITY (CODE, NAME, IS_ACTIVE) VALUES ('BV-TW', 'Benh vien Trung uong', 'Y');
INSERT INTO LIS_FACILITY (CODE, NAME, IS_ACTIVE) VALUES ('BV-DA', 'Benh vien Da khoa Thanh pho', 'Y');
INSERT INTO LIS_FACILITY (CODE, NAME, IS_ACTIVE) VALUES ('PK-QT', 'Phong kham Quan 7', 'Y');

INSERT INTO LIS_LAB_AREA (FACILITY_ID, CODE, NAME, IS_ACTIVE)
SELECT F.ID, 'HH', 'Huyet hoc', 'Y' FROM LIS_FACILITY F WHERE F.CODE = 'BV-TW';
INSERT INTO LIS_LAB_AREA (FACILITY_ID, CODE, NAME, IS_ACTIVE)
SELECT F.ID, 'SH', 'Sinh hoa', 'Y' FROM LIS_FACILITY F WHERE F.CODE = 'BV-TW';
INSERT INTO LIS_LAB_AREA (FACILITY_ID, CODE, NAME, IS_ACTIVE)
SELECT F.ID, 'VS', 'Vi sinh', 'Y' FROM LIS_FACILITY F WHERE F.CODE = 'BV-TW';

INSERT INTO LIS_LAB_AREA (FACILITY_ID, CODE, NAME, IS_ACTIVE)
SELECT F.ID, 'HH', 'Huyet hoc', 'Y' FROM LIS_FACILITY F WHERE F.CODE = 'BV-DA';
INSERT INTO LIS_LAB_AREA (FACILITY_ID, CODE, NAME, IS_ACTIVE)
SELECT F.ID, 'SH', 'Sinh hoa', 'Y' FROM LIS_FACILITY F WHERE F.CODE = 'BV-DA';

INSERT INTO LIS_LAB_AREA (FACILITY_ID, CODE, NAME, IS_ACTIVE)
SELECT F.ID, 'XN-TQ', 'Xet nghiem tong quat', 'Y' FROM LIS_FACILITY F WHERE F.CODE = 'PK-QT';
INSERT INTO LIS_LAB_AREA (FACILITY_ID, CODE, NAME, IS_ACTIVE)
SELECT F.ID, 'XN-NK', 'Xet nghiem noi khoa', 'Y' FROM LIS_FACILITY F WHERE F.CODE = 'PK-QT';

-- Demo account
-- Default seed password (plain text): Admin@123
-- PASSWORD_HASH generated by Argon2id and intended for backend argon2.verify()
INSERT INTO LIS_USER_ACCOUNT (USERNAME, DISPLAY_NAME, PASSWORD_HASH, IS_ACTIVE)
VALUES (
  'admin',
  'Administrator',
  '$argon2id$v=19$m=65536,t=3,p=4$4CxWk56JeikYfhCU+5GGFA$tBWvKIfXbEf+YNA5Hir2RbuZ9+4SlU987w4H78J9EO0',
  'Y'
);

-- Seed RBAC roles (5 actor groups)
INSERT INTO LIS_ROLE (CODE, NAME, IS_ACTIVE) VALUES ('reception_staff', 'Nhan vien tiep nhan', 'Y');
INSERT INTO LIS_ROLE (CODE, NAME, IS_ACTIVE) VALUES ('sample_collection_technician', 'Ky thuat vien lay mau', 'Y');
INSERT INTO LIS_ROLE (CODE, NAME, IS_ACTIVE) VALUES ('lab_technician', 'Ky thuat vien xet nghiem', 'Y');
INSERT INTO LIS_ROLE (CODE, NAME, IS_ACTIVE) VALUES ('lab_doctor', 'Bac si xet nghiem', 'Y');
INSERT INTO LIS_ROLE (CODE, NAME, IS_ACTIVE) VALUES ('system_admin', 'Quan tri he thong', 'Y');

-- Assign admin account to system_admin role
INSERT INTO LIS_USER_ROLE (USER_ID, ROLE_ID)
SELECT U.ID, R.ID
FROM LIS_USER_ACCOUNT U
JOIN LIS_ROLE R ON R.CODE = 'system_admin'
WHERE U.USERNAME = 'admin';

-- Explicit assignment for existing environment IDs
MERGE INTO LIS_USER_ROLE T
USING (
  SELECT
    'D8DC424DFE3E49429F0C206B4DD6F8E9' AS USER_ID,
    '794E3F46489A478C95E53ACA3CAD2346' AS ROLE_ID
  FROM DUAL
) S
ON (T.USER_ID = S.USER_ID AND T.ROLE_ID = S.ROLE_ID)
WHEN NOT MATCHED THEN
  INSERT (ID, USER_ID, ROLE_ID, ASSIGNED_AT)
  VALUES (RAWTOHEX(SYS_GUID()), S.USER_ID, S.ROLE_ID, SYSTIMESTAMP);

-- Grant admin scope to all active facility/lab areas
INSERT INTO LIS_USER_SCOPE (USER_ID, FACILITY_ID, LAB_AREA_ID, IS_ACTIVE)
SELECT U.ID, F.ID, A.ID, 'Y'
FROM LIS_USER_ACCOUNT U
JOIN LIS_FACILITY F ON F.IS_ACTIVE = 'Y'
JOIN LIS_LAB_AREA A ON A.FACILITY_ID = F.ID AND A.IS_ACTIVE = 'Y'
WHERE U.USERNAME = 'admin';

COMMIT;

-- ==========================================================
-- Optional query examples for backend integration
-- ==========================================================
-- loadFacilities():
-- SELECT ID, CODE, NAME, CASE WHEN IS_ACTIVE = 'Y' THEN 1 ELSE 0 END AS IS_ACTIVE
-- FROM LIS_FACILITY
-- WHERE IS_ACTIVE = 'Y'
-- ORDER BY NAME;

-- loadLabAreas(facilityId):
-- SELECT ID, FACILITY_ID, CODE, NAME, CASE WHEN IS_ACTIVE = 'Y' THEN 1 ELSE 0 END AS IS_ACTIVE
-- FROM LIS_LAB_AREA
-- WHERE FACILITY_ID = :facilityId
--   AND IS_ACTIVE = 'Y'
-- ORDER BY NAME;

-- submitLogin validation skeleton:
-- 1) Find active user by USERNAME
-- 2) Verify password hash in app service layer
-- 3) Check LIS_USER_SCOPE exists for USER_ID + FACILITY_ID + LAB_AREA_ID
-- 4) Insert LIS_SESSION + LIS_LOGIN_ATTEMPT_LOG(event_type='submit_success'|'submit_error')
